services:
  - type: web
    name: goldenagess
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/goldenage-0.0.1-SNAPSHOT.jar"
    plan: free
    region: singapore
