services:
  - type: web
    name: goldenages
    env: java
    buildCommand: |
      export JAVA_HOME=/opt/render/project/.java
      chmod +x mvnw
      ./mvnw clean package
    startCommand: java -jar target/goldenage-0.0.1-SNAPSHOT.jar
    plan: free
    region: Virginia (US East)
